#!/bin/bash

#
#	This is a Guardian script for the MTCore
#	The logic is as follows:
#	1) Start MTCore on the system start and try to detect abnormal exits due to runtime crash and restart the MTCore if needed
#	2) Monitor MTCore restarted gracefully and try to detect abnormal exits due to runtime crash and restart the MTCore if needed
#
#	Note: we assume we are working inside virtual console (screen)!!
#
# 	(c) MTSS Development aka Moontrader Development Team, 2024.
#
#set -x

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source ${SCRIPT_DIR}/MTGuardian.settings
source ${SCRIPT_DIR}/rawurlencode.inc.sh
source ${SCRIPT_DIR}/telegram_helper.sh

# changing current directory to MTCore directory
cd ${MT_CORE_DIR}


while true;
do
./MTCore  ${MT_CORE_ARGS} &
declare -i corePid=$!
SendTelegramMessage "Notice: MTCore on [${MT_CORE_SERVER_NAME}] succesfly started at `date`!"

# waiting for MTCore exit
wait $corePid

#check if MTCore exited gracefully
coreInfo="/tmp/${corePid}.cscdat"

if [ -f $coreInfo ] ; 
then
	SendTelegramMessage "Warning: MTCore crashed on server [${MT_CORE_SERVER_NAME}] at [`date`], trying restart..."
	rm -rf $coreInfo
else
	SendTelegramMessage "Notice: MTCore did clean exit on server [${MT_CORE_SERVER_NAME}] at [`date`], switching to monitoring mode!"
	break
fi

#wait 2 seconds before next loop
sleep 2
done

# monitoring section
while true;
do
#check if MTCore process was spawned
MTCore="`pidof MTCore`"
declare -i corePid=${MTCore[0]}

if (( $corePid < 2 )); then
    echo "No MTCore process(es) running, waiting a bit.."
    sleep 2
else
    SendTelegramMessage "Notice: Started monitoring MTCore with PID [${corePid}] on server [${MT_CORE_SERVER_NAME}] at [`date`]!"
    echo "Starting to monitor MTCore with PID=${corePid}"
    # waiting for MTCore exit - note, we can not use wait command here since we are not spawned it!!
    tail --pid=$corePid -f /dev/null

    #check if MTCore exited gracefully
    coreInfo="/tmp/${corePid}.cscdat"

    if [ -f $coreInfo ] ;
    then
	SendTelegramMessage "Warning: MTCore crashed on server [${MT_CORE_SERVER_NAME}] at [`date`], trying restart..."
	echo "Warning: MTCore crashed on server [${MT_CORE_SERVER_NAME}] at [`date`], trying restart..."
	rm -rf $coreInfo
	./MTCore  ${MT_CORE_ARGS} &
    else
	SendTelegramMessage "Notice: MTCore did clean exit on server [${MT_CORE_SERVER_NAME}] at [`date`], switching to monitoring mode!"
	echo "Notice: MTCore did clean exit on server [${MT_CORE_SERVER_NAME}] at [`date`], switching to monitoring mode!"
    fi
fi
sleep 2
done